# Generated by Django 5.2.7 on 2025-11-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='comm',
        ),
    ]
